[package]
name = "moonbeam-runtime-common"
authors = [ "PureStake" ]
description = "Common code shared between runtimes"
edition = "2021"
homepage = "https://moonbeam.network"
license = "GPL-3.0-only"
version = "0.8.0-dev"

[dependencies]
hex-literal = "0.3.4"
impl-trait-for-tuples = "0.2.1"
log = "0.4"

# Moonbeam
moonbeam-xcm-benchmarks = { git = "https://github.com/purestake/moonbeam", rev = "runtime-2201", optional = true, default-features = false }
pallet-asset-manager = { git = "https://github.com/purestake/moonbeam", rev = "runtime-2201", default-features = false }
pallet-author-mapping = { git = "https://github.com/purestake/moonbeam", rev = "runtime-2201", default-features = false }
pallet-ethereum-xcm = { git = "https://github.com/purestake/moonbeam", rev = "runtime-2201", default-features = false }
pallet-migrations = { git = "https://github.com/purestake/moonbeam", rev = "runtime-2201", default-features = false }
pallet-parachain-staking = { git = "https://github.com/purestake/moonbeam", rev = "runtime-2201", default-features = false }
pallet-randomness = { git = "https://github.com/purestake/moonbeam", rev = "runtime-2201", default-features = false }
pallet-xcm-transactor = { git = "https://github.com/purestake/moonbeam", rev = "runtime-2201", default-features = false }
precompile-utils = { git = "https://github.com/purestake/moonbeam", rev = "runtime-2201", default-features = false }
xcm-primitives = { git = "https://github.com/purestake/moonbeam", rev = "runtime-2201", default-features = false }

# Substrate
frame-support = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.37", default-features = false }
frame-system = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.37", default-features = false }
pallet-collective = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.37", default-features = false }
pallet-democracy = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.37", default-features = false }
pallet-preimage = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.37", default-features = false }
pallet-referenda = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.37", default-features = false }
pallet-scheduler = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.37", default-features = false }
sp-core = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.37", default-features = false }
sp-runtime = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.37", default-features = false }
sp-std = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.37", default-features = false }

# Frontier
fp-ethereum = { git = "https://github.com/purestake/frontier", branch = "moonbeam-polkadot-v0.9.37", default-features = false }
fp-evm = { git = "https://github.com/purestake/frontier", branch = "moonbeam-polkadot-v0.9.37", default-features = false }
pallet-base-fee = { git = "https://github.com/purestake/frontier", branch = "moonbeam-polkadot-v0.9.37", default-features = false }
pallet-evm = { git = "https://github.com/purestake/frontier", branch = "moonbeam-polkadot-v0.9.37", default-features = false, features = [ "forbid-evm-reentrancy" ] }

# Nimbus
pallet-author-inherent = { git = "https://github.com/purestake/nimbus", branch = "moonbeam-polkadot-v0.9.37", default-features = false }
pallet-author-slot-filter = { git = "https://github.com/purestake/nimbus", branch = "moonbeam-polkadot-v0.9.37", default-features = false }

# Polkadot
xcm = { git = "https://github.com/purestake/polkadot", branch = "moonbeam-polkadot-v0.9.37", default-features = false }
xcm-executor = { git = "https://github.com/purestake/polkadot", branch = "moonbeam-polkadot-v0.9.37", default-features = false }

[features]
std = [
	"fp-ethereum/std",
	"fp-evm/std",
	"frame-support/std",
	"pallet-asset-manager/std",
	"pallet-author-inherent/std",
	"pallet-author-mapping/std",
	"pallet-base-fee/std",
	"pallet-ethereum-xcm/std",
	"pallet-evm/std",
	"pallet-migrations/std",
	"pallet-parachain-staking/std",
	"pallet-randomness/std",
	"pallet-referenda/std",
	"pallet-scheduler/std",
	"pallet-xcm-transactor/std",
	"precompile-utils/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
	"xcm-executor/std",
	"xcm/std",
]
runtime-benchmarks = [ "pallet-referenda/runtime-benchmarks" ]
try-runtime = [
	"frame-support/try-runtime",
	"pallet-migrations/try-runtime",
]
