[workspace]

[package]
name = "rust-scripts"
edition = "2021"
homepage = "https://moonbeam.network"
license = "GPL-3.0-only"
version = "0.8.4"

[[bin]]
name = "migrate-imported"
path = "migrate-imported.rs"

[dependencies]
toml_edit = "0.19.3"
clap = { version = "4.1.6", features = ["derive"]}